### ISSUE TITLE
Tool is not working

### ISSUE THREAD

**Issue by lhamycodes** [jnafolayan/o2tv-dl#2]
Fails to download newly uploaded series on o2tveries.com

**Comment by jnafolayan** [comment]
Hey @lhamycodes 

This issue arises due to the new system O2TvSeries uses to store video files. Unfortunately, there isn't so much I can do to fix this with the current architecture. A complete rewrite will be necessary to accommodate the site's current system, and possibly any future modifications.

Just because I can, and as the last change I will make to this tool, I made it possible to select multiple episodes for download. You don't have to always invoke the command line tool for every new episode download. Enjoy :)

I might, however, work on building a better tool for a somewhat _better_ movies site. 

Cheers
